config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :movie_genres, except: [:destroy]
  resources :movie_directors, except: [:destroy]
  resources :movies, except: [:destroy] do
    patch 'publish', on: :member
    patch 'draft', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :movie_genre
  belongs_to :movie_director

  enum status: { unreleased: 0, released: 1}
  enum visibility: { draft: 0, published: 1}

  has_one_attached :poster
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  belongs_to :movie_genre
  has_many :movies
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  has_many :movie_directors
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.published
  end
end

app/controllers/movie_directors_controller.rb
class MovieDirectorsController < ApplicationController
  def index
    @movie_directors = MovieDirector.all
  end
  
  def show
    @movie_director = MovieDirector.find(params[:id])
    @movies = @movie_director.movies
  end

  def new
    @movie_director = MovieDirector.new
  end

  def create
    @movie_director = MovieDirector.new(movie_director_params)
    
    if @movie_director.save
      return redirect_to @movie_director, notice: 'Diretor cadastrado com sucesso.'
    end
    flash.now[:notice] = 'Não foi possível cadastrar o diretor.'
    render :new, status: 422
  end

  def edit
    @movie_director = MovieDirector.find(params[:id])
  end

  def update
    @movie_director = MovieDirector.find(params[:id])
    if @movie_director.update(movie_director_params)
      return redirect_to @movie_director, notice: 'Diretor atualizado com sucesso.'
    end
    flash.now[:notice] = 'Não foi possível atualizar o diretor.'
    render :edit, status: 422
  end

  private
  
  def movie_director_params
    params.require(:movie_director).permit(:name, :nationality, :birth_date, :movie_genre_id)
  end
end

app/controllers/movie_genres_controller.rb
class MovieGenresController < ApplicationController
  def index
    @movie_genres = MovieGenre.all
  end

  def show
    @movie_genre = MovieGenre.find(params[:id])
    @movies = @movie_genre.movies
  end

  def new
    @movie_genre = MovieGenre.new
  end

  def create
    @movie_genre = MovieGenre.new(movie_genre_params)
    
    if @movie_genre.save
      return redirect_to @movie_genre, notice: 'Gênero cadastrado com sucesso.'
    end
    flash.now[:notice] = 'Não foi possível cadastrar o gênero.'
    render :new, status: 422
  end

  def edit
    @movie_genre = MovieGenre.find(params[:id])
  end

  def update
    @movie_genre = MovieGenre.find(params[:id])
    if @movie_genre.update(movie_genre_params)
      return redirect_to @movie_genre, notice: 'Gênero atualizado com sucesso.'
    end
    flash.now[:notice] = 'Não foi possível atualizar o gênero.'
    render :edit, status: 422
  end

  private
  
  def movie_genre_params
    params.require(:movie_genre).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.published
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    
    if @movie.save
      return redirect_to @movie, notice: 'Filme cadastrado com sucesso.'
    end
    flash.now[:notice] = 'Não foi possível cadastrar o filme.'
    render :new, status: 422
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
     return redirect_to @movie, notice: 'Filme atualizado com sucesso.'
    end
    flash.now[:notice] = 'Não foi possível atualizar o filme.'
    render :edit, status: 422
  end

  def publish
    movie = Movie.find(params[:id])
    movie.published!
    return redirect_to movie_path(movie.id)
  end

  def draft
    movie = Movie.find(params[:id])
    movie.draft!
    return redirect_to movie_path(movie.id)
  end

  private
  
  def movie_params
    params.require(:movie).permit(:title, :release_year, :summary, :country, :duration, :movie_genre_id, :movie_director_id, :status, :poster)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Catálogo de Filmes</h1>

<dl>
<% @movies.each do |movie| %>
  <dt><%= link_to movie.title, movie %></dt>
  <dd><%= image_tag(movie.poster.variant(resize_to_limit: [200, 300])) if movie.poster.attached? %></dd>
  <dd><%= movie.release_year %></dd>
  <dd><%= movie.status %></dd>
<% end %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Cadastrar Filme', new_movie_path %> | <%= link_to 'Lista de Filmes', movies_path %></li>
          <li><%= link_to 'Cadastrar Gênero', new_movie_genre_path %> | <%= link_to 'Lista de Gêneros', movie_genres_path %></li>
          <li><%= link_to 'Cadastrar Diretor', new_movie_director_path %> | <%= link_to 'Lista de Diretores', movie_directors_path %></li></li>
        </ul>
      </nav>
    </header>
    <main>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>

     <%= yield %>
    </main>
  </body>
</html>

app/views/movie_directors/_form.html.erb
<%= form_with model: movie_director do |f| %>
  <%= f.label 'Nome' %>
  <%= f.text_field :name %>

  <%= f.label 'Nacionalidade' %>
  <%= f.text_field :nationality %>

  <%= f.label 'Data de nascimento' %>
  <%= f.date_field :birth_date %>

  <%= f.label 'Gênero favorito' %>
  <%= f.collection_select :movie_genre_id, MovieGenre.all, :id, :name %>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/movie_directors/edit.html.erb
<h1>Editar Diretor</h1>

<%= render partial: 'form', locals: { movie_director: @movie_director }%>

app/views/movie_directors/index.html.erb
<h1>Lista de Diretores</h1>

<ul>
<% @movie_directors.each do |director| %>
  <li><%= link_to director.name, director %></li>
<% end %>
</ul>

app/views/movie_directors/new.html.erb
<h1>Cadastrar Diretor</h1>

<%= render partial: 'form', locals: { movie_director: @movie_director }%>

app/views/movie_directors/show.html.erb
<h1>Diretor: <%= @movie_director.name %></h1>

<ul>
  <li><strong>Nacionalidade:</strong> <%= @movie_director.nationality %></li>
  <li><strong>Data de nascimento:</strong> <%= @movie_director.birth_date %></li>
  <li><strong>Gênero favorito:</strong> <%= @movie_director.movie_genre.name %></li>
</ul>

<h2>Filmes</h2>

<ul>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie %></li>
  <% end %>
</ul>

<%= link_to 'Editar Diretor', edit_movie_path %>

app/views/movie_genres/_form.html.erb
<%= form_with model: movie_genre do |f| %>
  <%= f.label 'Nome' %>
  <%= f.text_field :name %>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/movie_genres/edit.html.erb
<h1>Editar Gênero</h1>

<%= render partial: 'form', locals: { movie_genre: @movie_genre }%>

app/views/movie_genres/index.html.erb
<h1>Lista de Gêneros</h1>

<ul>
<% @movie_genres.each do |genre| %>
  <li><%= link_to genre.name, genre %></li>
<% end %>
</ul>

app/views/movie_genres/new.html.erb
<h1>Cadastrar Gênero</h1>

<%= render partial: 'form', locals: { movie_genre: @movie_genre }%>

app/views/movie_genres/show.html.erb
<h1>Filmes de <%= @movie_genre.name %></h1>

<ul>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie %></li>
  <% end %>
</ul>

<%= link_to 'Editar Gênero', edit_movie_genre_path %>

app/views/movies/_form.html.erb
<%= form_with model: movie do |f| %>
  <%= f.label 'Título' %>
  <%= f.text_field :title %>

  <%= f.label 'Ano de lançamento' %>
  <%= f.number_field :release_year %>

  <%= f.label 'Sinopse' %>
  <%= f.text_area :summary %>

  <%= f.label 'País' %>
  <%= f.text_field :country %>

  <%= f.label 'Duração' %>
  <%= f.number_field :duration %>

  <%= f.label 'Gênero' %>
  <%= f.collection_select :movie_genre_id, MovieGenre.all, :id, :name %>

  <%= f.label 'Diretor' %>
  <%= f.collection_select :movie_director_id, MovieDirector.all, :id, :name %>

  <%= f.label 'Status' %>
  <%= f.select :status, Movie.statuses.keys.map { |status| [status.humanize, status] } %>

  <%= f.label :poster, "Pôster do filme" %>
  <%= f.file_field :poster %>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editar Filme</h1>

<%= render partial: 'form', locals: { movie: @movie }%>

app/views/movies/index.html.erb
<h1>Lista de Filmes</h1>

<dl>
<% @movies.each do |movie| %>
  <dt><%= link_to movie.title, movie %></dt>
  <dd><%= image_tag(movie.poster.variant(resize_to_limit: [200, 300])) if movie.poster.attached? %></dd>
  <dd><%= movie.release_year %></dd>
  <dd><%= movie.status %></dd>
<% end %>
</dl>

app/views/movies/new.html.erb
<h1>Cadastrar Filme</h1>

<%= render partial: 'form', locals: { movie: @movie }%>

app/views/movies/show.html.erb
<h1>Filme: <%= @movie.title %></h1>

<%= image_tag(@movie.poster.variant(resize_to_limit: [200, 300])) if @movie.poster.attached? %>

<ul>
  <li><strong>Ano de lançamento:</strong> <%= @movie.release_year %></li>
  <li><strong>Sinopse:</strong> <%= @movie.summary %></li>
  <li><strong>País:</strong> <%= @movie.country %></li>
  <li><strong>Duração:</strong> <%= @movie.duration %> minutos</li>
  <li><strong>Gênero:</strong> <%= link_to @movie.movie_genre.name, @movie.movie_genre %></li>
  <li><strong>Diretor:</strong> <%= link_to @movie.movie_director.name, @movie.movie_director %></li>
  <li><strong>Status:</strong> <%= @movie.status %></li>

  <li><strong>Visibilidade:</strong> <%= @movie.visibility %></li> 
</ul>

<%= link_to 'Editar Filme', edit_movie_path %>

<% if @movie.draft? %>
  <%= button_to 'Publicar', publish_movie_path, { method: 'patch' } %>
<% else %>
  <%= button_to 'Despublicar', draft_movie_path, { method: 'patch' } %>
<% end %>